name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: config
      run: ./configure
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: djb2-linux-x64
        path: djb2
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - name: config
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: gcc make
      - name: make
        run: make
      - name: artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: djb2-windows-x64
          path: djb2.exe
          
